[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
evm_version = "shanghai"
gas_reports = ["*"]
remappings = ["openzeppelin-erc20-basic/=lib/openzeppelin-contracts/contracts/token/ERC20/",
    "openzeppelin-math/=lib/openzeppelin-contracts-upgradeable/contracts/utils/math/",
    "openzeppelin-erc20/=lib/openzeppelin-contracts-upgradeable/contracts/token/ERC20/",
    "openzeppelin-erc20-extensions/=lib/openzeppelin-contracts-upgradeable/contracts/token/ERC20/extensions",
    "openzeppelin-utils/=lib/openzeppelin-contracts-upgradeable/contracts/utils/",
    "openzeppelin-proxy/=lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[profile.etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[profile.fuzz]
runs = 1024
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[fuzz]
runs = 1024

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
