on: [pull_request]
name: PR Coverage
env:
  SEPOLIA_RPC_URL: "https://eth-sepolia.g.alchemy.com/v2/nDLhuduH3_4OsbT9dVHq_Sa4E9bwlcOb"
  MAINNET_RPC_URL: "https://eth-mainnet.g.alchemy.com/v2/3WdjR5UrB3GMMl1VG3pEVtnLMdce914Z"
  TEST_RPC_URL: "https://eth-sepolia.g.alchemy.com/v2/nDLhuduH3_4OsbT9dVHq_Sa4E9bwlcOb"
  DEPLOYMENT_NETWORK: TEST
  ACCESS_MANAGER_ADMIN_TEST: ""
  ACCESS_MANAGER_ADDRESS_TEST: ""
  DURATION_TEST: 10000000
  PROTOCOL_FEE_TEST: 0
  TOKENIZATION_FEE_TEST: 0
  YIELD_FEE_TEST: 0
  PT_FLASH_LOAN_FEE_TEST: 0
  FEE_COLLECTOR_TEST: 0
  PROXY_ADMIN_ADDR_TEST: ""
  REGISTRY_ADDR_TEST: ""
  ASSET_ADDR_TEST: ""
  IBT_ADDR_TEST: ""
  PT_INSTANCE_ADDR_TEST: ""
  FACTORY_ADDR_TEST: ""
  PT_BEACON_PROXY_ADDR_TEST: ""
  INITIAL_LIQUIDITY_IBT_SEPOLIA: 0
  MIN_PT_SHARES_SEPOLIA: 0

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        working-directory: src
        run: |
          forge --version
          forge build --sizes
        id: build
      - name: Running coverage
        run: |
          forge coverage --no-match-test ".*[fF]uzz.*" --report lcov
          sudo apt-get install lcov
          lcov --remove ./lcov.info -o ./lcov.info 'src/util/*' 'script/*' 'src/mocks/*' 'test/*'
      - name: Report coverage
        uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          lcov-file: ./lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Enforce coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
      #   with:
      #     path: ./lcov.info
      #     min_coverage: 90